apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: todo_db
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: passwd
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
          image: mongodb/mongodb-community-server:6.0-ubi8
          name: container-mongo
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/mongo-init.js
              name: mongodb-cm0
              readOnly: true
              subPath: mongo-init.js
            - mountPath: /data/db
              name: mongo-data
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: mongo-init.js
                path: mongo-init.js
            name: mongodb-cm0
          name: mongodb-cm0
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data
